#!/usr/bin/env bash

#
# Create the compressed backups for created databases
#

if [[ "$(id -u)" -ne "0" ]]; then
  echo "Please, run this with the root user or sudo."
  exit 1
elif [[ -z "$1" ]]; then
  echo "Undefined directory arguments"
  echo "Usage: sudo ./mysql-autobackup directory"
  exit 1
elif ! command -v mariadb >/dev/null 2>&1 || ! command -v mysql >/dev/null 2>&1; then
  echo "Missing MySQL command"
  exit 1
fi

MYSQL_DIRECTORY="${1%*/}"
if [[ ! -d "$MYSQL_DIRECTORY" ]]; then
  mkdir -p "$MYSQL_DIRECTORY"
fi

MYSQL_COMMAND="mysql"
MYSQLDUMP_COMMAND="mysqldump"
if command -v mariadb >/dev/null 2>&1; then
  MYSQL_COMMAND="mariadb"
  MYSQLDUMP_COMMAND="mariadb-dump"
fi
MYSQL_EXCLUDE_DATABASES=(
  information_schema
  mysql
  performance_schema
  phpmyadmin
  sys
)

for database in $($MYSQL_COMMAND -sNe 'show databases;'); do
  if [[ "$(printf '%s\n' "${MYSQL_EXCLUDE_DATABASES[@]}" | grep -cx -- "$database")" -gt "1" ]]; then
    $MYSQLDUMP_COMMAND --databases "$database" | gzip -k9 >"$MYSQL_DIRECTORY/$database.sql.gz"
  fi
done
