#!/usr/bin/env bash
#
# Create the compressed backups for created databases
#

if [[ "$(id -u)" -ne "0" ]]; then
  echo "Please, run this with the root user or sudo."
  exit 1
elif [[ -z "$1" ]]; then
  echo "Undefined directory arguments"
  echo "Usage: sudo ./mysql-autobackup directory"
  exit 1
elif ! command -v mariadb >/dev/null 2>&1 || ! command -v mysql >/dev/null 2>&1; then
  echo "Missing MySQL command"
  exit 1
fi

MYSQL_DIRECTORY="${1%*/}"
if [[ ! -d "$MYSQL_DIRECTORY" ]]; then
  mkdir -p "$MYSQL_DIRECTORY"
fi

MYSQL_COMMAND="mysql"
MYSQLDUMP_COMMAND="mysqldump"
if command -v mariadb >/dev/null 2>&1; then
  MYSQL_COMMAND="mariadb"
  MYSQLDUMP_COMMAND="mariadb-dump"
fi

for database in $($MYSQL_COMMAND -sNe 'show databases;'); do
  case "$database" in
  mysql | performance_schema | phpmyadmin | sys | information_schema) ;;
  *)
    echo "Creating the $database backup"
    # $MYSQLDUMP_COMMAND --databases --quick --single-transaction "$database" >"$MYSQL_DIRECTORY/$database.sql"
    $MYSQLDUMP_COMMAND --databases --quick --single-transaction "$database" | gzip -k9 >"$MYSQL_DIRECTORY/$database.sql.gz"
    ;;
  esac
done

# echo "Creating the full backup"
# $MYSQLDUMP_COMMAND --all-databases --quick --single-transaction >"$MYSQL_DIRECTORY/databases.sql"
# $MYSQLDUMP_COMMAND --all-databases --quick --single-transaction | gzip -k9 >"$MYSQL_DIRECTORY/databases.sql.gz"
